//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd d MMM H:mm.
        /// </summary>
        internal static string AgeFormat {
            get {
                return ResourceManager.GetString("AgeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return confirm(&apos;Are you certain you want to delete THE WHOLE EVENT? This action cannot be undone.&apos;);.
        /// </summary>
        internal static string EventDeleteConfirmationFunc {
            get {
                return ResourceManager.GetString("EventDeleteConfirmationFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return confirm(&apos;Are you certain you want to delete THE WHOLE GROUP? This action cannot be undone.&apos;);.
        /// </summary>
        internal static string GroupDeleteConfirmationFunc {
            get {
                return ResourceManager.GetString("GroupDeleteConfirmationFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide additional clean-up controls.
        /// </summary>
        internal static string HideAdvPointsCleanUp {
            get {
                return ResourceManager.GetString("HideAdvPointsCleanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///FROM ( 
        ///       SELECT G.*, U.UserName,
        ///            (SELECT COUNT(*) FROM GroupTracker GT WHERE GT.GroupId = G.Id) AS TrackersCount 
        ///       FROM [Group] G JOIN aspnet_Users U ON G.UserId = U.UserId
        ///       WHERE G.IsPublic=1 OR @IsAdmin=1
        ///) rst
        ///WHERE rst.TrackersCount &gt; 1 AND (@UserId IS NULL OR UserId&lt;&gt;@UserId).
        /// </summary>
        internal static string SelectPublicGroupsSql {
            get {
                return ResourceManager.GetString("SelectPublicGroupsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///CASE 
        ///	WHEN up.IsSimpleEventsModel = 0 OR	
        ///			up.DefaultEventId = g.EventId 
        ///		THEN g.EventId 
        ///	ELSE NULL 
        ///END AS EventId,
        ///up.IsSimpleEventsModel,
        ///e.Name AS EventName,
        ///g.Id, 
        ///g.Name, 
        ///g.NewestCoordTs, 
        ///g.NewestLat, 
        ///g.NewestLon, 
        ///g.UserId, 
        ///g.ViewsNum, 
        ///g.PageUpdatesNum, 
        ///g.IsPublic,
        ///e.Name As EventName, 
        ///(SELECT COUNT(*) FROM Task T
        ///	JOIN Waypoint w ON T.WaypointId = w.Id
        ///	WHERE w.EventId = g.EventId
        ///) AS TaskWptCount,
        ///(SELECT COUNT(*) FROM GroupTracker gt WHERE gt.GroupId =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectUserGroupsSql {
            get {
                return ResourceManager.GetString("SelectUserGroupsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show additional clean-up controls....
        /// </summary>
        internal static string ShowAdvPointsCleanUp {
            get {
                return ResourceManager.GetString("ShowAdvPointsCleanUp", resourceCulture);
            }
        }
    }
}
